### ISSUE TITLE
Tests fail with "Class Counter for Durable Object COUNTER not found"

### ISSUE THREAD

**Issue by ptim** [mrbbot/miniflare-typescript-esbuild-jest#5]
Hi! Thanks for the miniflare and this setup 🙏

Just looking to provide a minimal repro for another issue, and ran into this first… will investigate and offer a PR if I figure it out 👍

Running on a clean install at https://github.com/mrbbot/miniflare-typescript-esbuild-jest/commit/fbf3fcba3f6f6afde9617d77dc1cd5b2afbc2524 and node v16.13.0:

```bash
rm -rf node_modules && npm install && npm test
```

```bash
 FAIL  test/response.spec.ts
  ● Test suite failed to run

    DurableObjectError [ERR_CLASS_NOT_FOUND]: Class Counter for Durable Object COUNTER not found

      at DurableObjectsPlugin.reload (file:/Users/ptim/Documents/Projects/New-Atlas/source/miniflare-typescript-esbuild-jest/node_modules/@miniflare/durable-objects/src/plugin.ts:202:15)

 FAIL  test/index.spec.ts
  ● Test suite failed to run

    DurableObjectError [ERR_CLASS_NOT_FOUND]: Class Counter for Durable Object COUNTER not found

      at DurableObjectsPlugin.reload (file:/Users/ptim/Documents/Projects/New-Atlas/source/miniflare-typescript-esbuild-jest/node_modules/@miniflare/durable-objects/src/plugin.ts:202:15)

 FAIL  test/counter.spec.ts
  ● Test suite failed to run

    DurableObjectError [ERR_CLASS_NOT_FOUND]: Class Counter for Durable Object COUNTER not found

      at DurableObjectsPlugin.reload (file:/Users/ptim/Documents/Projects/New-Atlas/source/miniflare-typescript-esbuild-jest/node_modules/@miniflare/durable-objects/src/plugin.ts:202:15)
```

**Comment by ptim** [comment]
Oops, sorry! I had `wrangler dev` running in another tab; tests pass just fine when there's no competition over port 8787!
